-- Up
CREATE TABLE COMMAND_EXECUTION(
    START_TIME BIGINT NOT NULL,
    COMMAND_NAME VARCHAR NOT NULL,
    COMMAND_SCRIPT VARCHAR NOT NULL,
    ERROR VARCHAR,
    EXIT_CODE INT,
    EXIT_SIGNAL VARCHAR,
    OUTPUT VARCHAR,
    PRIMARY KEY (START_TIME, COMMAND_NAME)
);

-- Down
DROP TABLE COMMAND_EXECUTION;
