-- Up
CREATE TABLE ALLOWED_LOG (
    ABSOLUTE_LOG_FILE_PATH VARCHAR PRIMARY KEY
);

CREATE TABLE COMMAND (
    ID BLOB PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    SCRIPT VARCHAR NOT NULL
);

CREATE TABLE COMMAND_EXECUTION (
    COMMAND_ID BLOB NOT NULL,
    START_TIME BIGINT NOT NULL,
    STATUS INTEGER NOT NULL,
    END_OF_LINE VARCHAR NOT NULL,
    OUTPUT VARCHAR NOT NULL,
    PRIMARY KEY(COMMAND_ID, START_TIME)
);

-- Down
DROP TABLE ALLOWED_LOG;
DROP TABLE COMMAND_EXECUTION;
DROP TABLE COMMAND;
